# fly.toml app configuration file generated for app-proxy on 2024-02-09T17:06:02-05:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'app-proxy'
primary_region = 'mia'

[env]

PORT = "3000"
SHOPIFY_APP_URL = "https://app-proxy.fly.dev"
SHOPIFY_API_KEY = "09a23ad9e3fb706d9af55a0519512095"
SCOPES = "write_products"


[build]

[http_service]
  internal_port = 3000
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 0
  processes = ['app']

[[vm]]
  cpu_kind = 'shared'
  cpus = 1
  memory_mb = 1024
